### PR TITLE
Fix bug that allows user to edit to existing event time

### LINKED ISSUE #217: Edit event allows for overlapping event

### PR DESCRIPTION
**Pull request by JrmCkh**
- Added `hasEventAtTime` method to edit event (to check for overlap)
- `hasEventAtTime` uses `existsAtTime` method, where it counts itself (the current event) as another event (thus, adding `hasEventAtTim`e would prevent current to be edited to its own time)
- Modified `existsAtTime` method to exclude `currentEvent`
- Overloading of `hasEventAtTime` to prevent modifying of other methods that uses `hasEventAtTime`

Resolves #217

### CODE REVIEW

File: src/main/java/ezschedule/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -92,10 +93,12 @@ public CommandResult execute(Model model) throws CommandException {
         Event eventToEdit = lastShownList.get(index.getZeroBased());
         Event editedEvent = createEditedEvent(eventToEdit, editEventDescriptor);
 
-        if (!eventToEdit.equals(editedEvent) && model.hasEvent(editedEvent)) {
-            throw new CommandException(MESSAGE_DUPLICATE_EVENT);
-        } else if (editedEvent.getEndTime().isBefore(editedEvent.getStartTime())) {
+        if (editedEvent.getEndTime().isBefore(editedEvent.getStartTime())) {
             throw new CommandException(MESSAGE_EVENT_END_TIME_EARLIER_THAN_START_TIME);
+        } else if (!eventToEdit.equals(editedEvent) && model.hasEvent(editedEvent)) {
```
Comment (lhy-hoyin) [inline src/main/java/ezschedule/logic/commands/EditCommand.java:98]: wrt `!eventToEdit.equals(editedEvent)`, assuming that checks ensured that at least something is edited, then this statement will always be `true`. Possible to remove to improve code quality?

**Review by lhy-hoyin — CHANGES_REQUESTED** [review]
Perhaps also add a test case to cover `model.hasEventAtTime(eventToEdit, editedEvent`)?

**Review by lhy-hoyin — APPROVED** [review]
LGTM

File: src/main/java/ezschedule/logic/commands/EditCommand.java (hunk 1 above)
Comment (JrmCkh) [reply src/main/java/ezschedule/logic/commands/EditCommand.java:98]: Nope. Causes 1 of the test to fail with the change
