### PR TITLE
Fix wrong calendar event name bug

### LINKED ISSUE #125: [PE-D][Tester C] List and calendar dont match
i recurred both the dance and sleep events but in the calendar it shows 2 of dance events on each day, when it supposed to show 1 dance and 1 sleep event on each day.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: linustws/ped#4

### PR DESCRIPTION
**Pull request by JrmCkh**
1. Improve code quality in Calendar class
2. Improve code quality in CalendarBox class
3. Changed typo in "Calender/calender" to "Calendar/calender"
4. Fixed the bug of displaying the wrong calendar event name

Resolves #125

### CODE REVIEW

File: src/main/java/ezschedule/ui/Calendar.java [hunk 1]
```diff
@@ -160,16 +169,23 @@ private boolean isToday(int currentDate) {
...
     }
 
-    private boolean isNotLeapYear() {
+    private boolean isLeapYear() {
+        // Centuries year that are leap year are divisible by 400
         boolean isCenturyYear = date.getYear() % 100 == 0;
         if (isCenturyYear) {
-            return date.getYear() % 4 != 0 && monthMaxDate == 29 && date.getYear() % 400 != 0;
+            return date.getYear() % 400 == 0;
         }
```
Comment (lhy-hoyin) [inline src/main/java/ezschedule/ui/Calendar.java:177]: Good job on the cleaner logic!

File: src/main/java/ezschedule/ui/CalendarBox.java [hunk 2]
```diff
@@ -84,24 +84,26 @@ private void setToday(boolean isToday) {
...
+
             } else if (events.size() > 2) {
-                Label moreEvents = new Label("...");
-                setEventLabelStyle(moreEvents);
-                calendarEvents.getChildren().add(moreEvents);
+                String moreEvents = "...";
+                setEventLabel(moreEvents);
             }
         }
     }
```
Comment (lhy-hoyin) [inline src/main/java/ezschedule/ui/CalendarBox.java:109]: Would it be better to use [guard clauses](https://medium.com/@scadge/if-statements-design-guard-clauses-might-be-all-you-need-67219a1a981a) here instead, to reduce the code indentation, making it easier to read?

File: src/main/java/ezschedule/ui/CalendarBox.java [hunk 3]
```diff
@@ -61,7 +63,9 @@ public CalendarBox(boolean isFind, boolean isToday, String date,
     @FXML
     public void handleListEvents() {
         if (events != null) {
-            filterExecutor.updateFilteredEventList(new EventMatchesDatePredicate(events.get(0).getDate()));
+            int firstEventIndex = 0;
+            Date date = events.get(firstEventIndex).getDate();
+            filterExecutor.updateFilteredEventList(new EventMatchesDatePredicate(date));
         }
     }
```
Comment (lhy-hoyin) [inline src/main/java/ezschedule/ui/CalendarBox.java:70]: Optionally, guard clauses can be used here.

**Review by lhy-hoyin — CHANGES_REQUESTED** [review]
Generally good. But code can be improved (see conversations).

**Review by lhy-hoyin — APPROVED** [review]
LGTM
